version: "3.3"

services:
  api:
    build:
      context: .
    image: registry.gitlab.com/intellidrone/api_new:${API_VERSION:-latest}
    environment:
      SWAGGER_HOST: ${SWAGGER_HOST:-http://localhost:${PORT}}
      SWAGGER_BASE_PATH: ${SWAGGER_BASE_PATH:-/api/}
      DB_MAIN_CLIENT: ${DB_MAIN_CLIENT:-docker}
      DATABASE_FILE: ${DB_MAIN_CLIENT:-./assets/database.json}
      JWT_FILE: ${DB_MAIN_CLIENT:-./assets/key.b64.pub}
    ports:
      - "3000:${PORT:-3000}"
    networks:
      - db
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
    ports:
      - "27017:${PORT_MONGO:-27017}"
    volumes:
      - ./data:/data/db
    networks:
      - db

networks:
  db:
    driver: overlay