version: "3.3"

services:
  api:
    environment:
      SWAGGER_HOST: localhost:${PORT:-3000}
      SWAGGER_BASE_PATH: /
      DB_MAIN_CLIENT: docker
      DATABASE_FILE: ./database.json
      JWT_FILE: ./keys/key.b64.pub
      APP_TOKENS_FILE: ./app_tokens.json
    volumes:
      - ./src:/usr/app/src
    command:
      - /usr/local/bin/node
      - "--inspect-brk=0.0.0.0:9229"
      - src/server.js
      - "-r dotenv/config"
    ports:
      - "3000:${PORT:-3000}"
      - "9229:9229"