version: "3.3"

services:
  api:
    build:
      context: .
    image: registry.gitlab.com/intellidrone/api_new:${API_VERSION:-latest}
    environment:
      SWAGGER_HOST: ${SWAGGER_HOST:-localhost:${PORT}}
      SWAGGER_BASE_PATH: ${SWAGGER_BASE_PATH:-/api/}
      DB_MAIN_CLIENT: ${DB_MAIN_CLIENT:-docker}
      DATABASE_FILE: ${DATABASE_FILE:-./assets/database.json}
      JWT_FILE: ${JWT_FILE:-./assets/key.b64.pub}
      APP_TOKENS_FILE: ${APP_TOKENS_FILE:-./app_tokens.json}
      PORT: ${PORT:-3000}
    volumes:
      - ./data/node:/usr/app/assets
    ports:
      - "3000:${PORT:-3000}"
    networks:
      - db
    depends_on:
      - database
  database:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 'DockerPassWORD'
    ports:
      - "27017:${PORT_MONGO:-27017}"
    volumes:
      - ./data/db:/data/db
    networks:
      - db

networks:
  db:
    driver: overlay