version: "3.3"

services:
  api:
    volumes:
      - ./:/usr/src/
    command:
      - node server.js
      - "--inspect-brk=0.0.0.0"
      - "."
    ports:
      - "3000:${PORT:-3000}"
      - "9229:9229"